# Generated by Django 5.2.5 on 2025-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_document_raw_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='document',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='document',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='document',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Национальность'),
        ),
        migrations.AddField(
            model_name='document',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
