# Generated by Django 5.2.5 on 2025-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_birth_date_document_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='jpg_file',
            field=models.ImageField(blank=True, null=True, upload_to='jpgs/', verbose_name='JPG изображение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', verbose_name='PDF файл'),
        ),
    ]
