# Generated by Django 5.2.5 on 2025-08-25 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_jpg_file_alter_document_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='test_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата тестирования'),
        ),
    ]
